import type { Metadata } from "next";
import { Marcellus, Urbanist } from "next/font/google";
import "@fancyapps/ui/dist/fancybox/fancybox.css";
import "../scss/main.scss";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const marcellus = Marcellus({
  weight: "400",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Kalpataru Signature",
    default: "Kalpataru Signature",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${marcellus.className} ${urbanist.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
